
services:
  storage:
    image: redis
    volumes: 
      - ./counter/data:/data
  counter:
    build: ./
    restart: always
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    
  main:
    image: alyonach/counter:new
    volumes: 
      - ./main_project/:/app
    restart: always
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3002/
    working_dir: /app
    depends_on:
      - counter
    command: ["npm", "run", "dev"]