services:
  storage:
    image: redis
    volumes:
      - redis_date:/data
  counterr:
    build: .
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    links:
    - storage
volumes:
  redis_date: {}

