
services:
  storage:
    image: redis
    volumes: 
      - ./counter/data:/data
  counter:
    build: ./
    restart: always
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    
  main:
    build: ./main_project
    restart: always
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3002/
    depends_on:
      - counter
      - mongo
    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/